# Generated by Django 3.0.3 on 2020-04-18 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'No blank comments allowed!')]),
        ),
    ]
